USE MASTER
GO

DROP DATABASE BD_MATRICULA
GO

CREATE DATABASE BD_MATRICULA
GO

USE BD_MATRICULA
GO

CREATE TABLE TB_USUARIO(
	DNI			VARCHAR(8),
	NOMBRES		VARCHAR(200),
	APELLIDOS	VARCHAR(200),
	USUARIO		VARCHAR(100),
	CLAVE		VARCHAR(100)
)
GO

CREATE TABLE TB_ALUMNO(
	DNI			VARCHAR(8),
	NOMBRES		VARCHAR(200),
	APELLIDOS	VARCHAR(200),
	PADRE_DNI	VARCHAR(8)		
)
GO

INSERT INTO TB_USUARIO VALUES('43811752','JORGE LUIS','CAMARENA CUEVA','JCAMARENAC','1234')
INSERT INTO TB_USUARIO VALUES('11111111','JORGE DANIEL','ROZAS VARGAS','JROZASV','1234')
INSERT INTO TB_USUARIO VALUES('22222222','VANNESA','LESCANO PALACIOS','VLESCANOP','1234')
INSERT INTO TB_USUARIO VALUES('33333333','JUAN ENRIQUE','LLANOS SILVA','JLLANOSS','1234')
INSERT INTO TB_USUARIO VALUES('44444444','MARTIN MANUEL','HIJAR CONTRERAS','MHIJARC','1234')

INSERT INTO TB_ALUMNO VALUES('55555555','JORGE JOSE','CAMARENA AQUINO','43811752')
INSERT INTO TB_ALUMNO VALUES('66666666','ALONSO FREDY','CAMARENA AQUINO','43811752')
INSERT INTO TB_ALUMNO VALUES('77777777','CARLOS ANTONIO','ROZAS FERNANDEZ','11111111')
GO

CREATE PROCEDURE USP_INGRESAR_USUARIO 
@USUARIO	VARCHAR(100),
@CLAVE		VARCHAR(100)
AS
SELECT DNI,NOMBRES,APELLIDOS FROM TB_USUARIO WHERE USUARIO=@USUARIO AND CLAVE=@CLAVE
GO

CREATE PROCEDURE USP_LISTAR_HIJOS
@DNI VARCHAR(8)
AS
SELECT DNI,APELLIDOS+', '+NOMBRES AS 'NombreEstudiante' FROM TB_ALUMNO WHERE PADRE_DNI = @DNI
GO

CREATE PROCEDURE USP_OBTENER_HIJO
@DNI VARCHAR(8)
AS
SELECT NOMBRES, APELLIDOS FROM TB_ALUMNO WHERE DNI=@DNI
GO

CREATE PROCEDURE USP_ACTUALIZAR_HIJO
@DNI		VARCHAR(8),
@NOMBRES	VARCHAR(200),
@APELLIDOS	VARCHAR(200)
AS
UPDATE TB_ALUMNO
SET
	NOMBRES = @NOMBRES,
	APELLIDOS = @APELLIDOS
WHERE DNI=@DNI
GO

CREATE PROCEDURE USP_OBTENER_USUARIO
@DNI VARCHAR(8)
AS
SELECT NOMBRES,APELLIDOS,USUARIO,CLAVE FROM TB_USUARIO WHERE DNI=@DNI
GO

CREATE PROCEDURE USP_ACTUALIZAR_USUARIO
@DNI		VARCHAR(8),
@NOMBRES	VARCHAR(200),
@APELLIDOS	VARCHAR(200),
@USUARIO	VARCHAR(100),
@CLAVE		VARCHAR(100)
AS
UPDATE TB_USUARIO
SET
	NOMBRES = @NOMBRES,
	APELLIDOS = @APELLIDOS,
	CLAVE = @CLAVE
WHERE DNI=@DNI
	